import DANMU_MSG from './DANMU_MSG'
import WATCHED_CHANGE from './WATCHED_CHANGE'
import SUPER_CHAT_MESSAGE from './SUPER_CHAT_MESSAGE'
import GUARD_BUY from './GUARD_BUY'
import SEND_GIFT from './SEND_GIFT'

export default {
  DANMU_MSG,
  WATCHED_CHANGE,
  SUPER_CHAT_MESSAGE,
  GUARD_BUY,
  SEND_GIFT,
}